
name: Python application

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: git config --global url."https://${{ secrets.MACHINEUSER_ACTIONS_PAT }}@github.com/".insteadOf ssh://git@github.com/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-recording
        python -m pip install -r requirements.txt
    - name: Test with pytest
      env:
        EXIST_DEV_URL: http://ec2-184-73-188-210.compute-1.amazonaws.com:8080/exist/rest
      run: |
        python -m pytest tests --record-mode=none
