# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master", "main", "devel"]
  pull_request:
    branches: ["master", "main", "devel"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Set github url and credentials
        run: |
          /usr/bin/git config --global --add url."https://${{ secrets.MACHINEUSER_ACTIONS_PAT }}:x-oauth-basic@github".insteadOf ssh://git@github
          /usr/bin/git config --global --add url."https://${{ secrets.MACHINEUSER_ACTIONS_PAT }}:x-oauth-basic@github".insteadOf https://github
          /usr/bin/git config --global --add url."https://${{ secrets.MACHINEUSER_ACTIONS_PAT }}:x-oauth-basic@github".insteadOf git@github
          /usr/bin/git config --global --add url."https://${{ secrets.MACHINEUSER_ACTIONS_PAT }}:x-oauth-basic@github".insteadOf git+ssh@github

      - name: Install the project
        run: uv sync --locked --dev

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen python -m pytest
